# Generated by Django 3.1.2 on 2020-10-18 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=120)),
                ('Last_Name', models.CharField(max_length=120)),
                ('Hire_status', models.CharField(max_length=120)),
                ('Hire_date', models.DateField()),
                ('Rate', models.IntegerField()),
                ('Permit', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
