# Generated by Django 3.1.2 on 2020-10-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employee'),
        ('inventory', '0002_auto_20201018_1405'),
        ('production', '0002_auto_20201018_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_tracker',
        ),
    ]
