# Generated by Django 3.1.2 on 2020-10-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_box_amt', models.IntegerField()),
                ('pre_roll_amt', models.IntegerField()),
                ('box_amt', models.IntegerField()),
                ('label_amount', models.IntegerField()),
                ('canna_sticker_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pre_roll_1g_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_roll_amt', models.IntegerField()),
                ('cone_amt', models.IntegerField()),
                ('canna_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preroll_half_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_roll_amt', models.IntegerField()),
                ('cone_amt', models.IntegerField()),
                ('canna_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='tube_2half_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_2half_amt', models.IntegerField()),
                ('pre_roll_amt', models.IntegerField()),
                ('plastic_tube', models.IntegerField()),
                ('sticker', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tube_full_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_2half_amt', models.IntegerField()),
                ('pre_roll_amt', models.IntegerField()),
                ('plastic_tube', models.IntegerField()),
                ('sticker', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Production_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
                ('Count', models.IntegerField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee_tracker')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.tasks')),
            ],
        ),
    ]
