# Generated by Django 3.1.2 on 2020-10-29 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='A_bud', max_length=120)),
                ('finished_product_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('input1', models.CharField(default='A_bud', max_length=120)),
                ('input1_amt', models.IntegerField(default='1')),
                ('input2', models.CharField(default='B_bud', max_length=120)),
                ('input2_amt', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_roll_1g_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='1g_open_pre_roll', max_length=120)),
                ('pre_roll_amt', models.IntegerField(default='1')),
                ('input1', models.CharField(default='cone', max_length=120)),
                ('cone_amt', models.IntegerField(default='1')),
                ('input2', models.CharField(default='cannabis grams', max_length=120)),
                ('canna_amount', models.DecimalField(decimal_places=2, default='1', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Preroll_half_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='halfg_open_pre_roll', max_length=120)),
                ('pre_roll_amt', models.IntegerField(default='1')),
                ('input1', models.CharField(default='cone', max_length=120)),
                ('cone_amt', models.IntegerField(default='1')),
                ('input2', models.CharField(default='cannabis grams', max_length=120)),
                ('canna_amount', models.DecimalField(decimal_places=2, default='.50', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=120)),
                ('finished_product', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Trimming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='A_bud', max_length=120)),
                ('finished_product_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('finished_product_b', models.CharField(default='B_bud', max_length=120)),
                ('finished_product2_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Twisting_Preroll_half_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='halfg_pre_roll', max_length=120)),
                ('pre_roll_amt', models.IntegerField(default='1')),
                ('input1_amt', models.IntegerField(default='1')),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.preroll_half_manuf')),
            ],
        ),
        migrations.CreateModel(
            name='Unwrapped_Box_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='Unwrapped_box', max_length=120)),
                ('finished_amt', models.IntegerField(default='1')),
                ('pre_roll_amt', models.IntegerField(default='10')),
                ('input2', models.CharField(default='Box', max_length=120)),
                ('box_amt', models.IntegerField(default='1')),
                ('input3', models.CharField(default='Box_Label', max_length=120)),
                ('label_amount', models.IntegerField(default='1')),
                ('input4', models.CharField(default='cannasticker', max_length=120)),
                ('canna_sticker_amount', models.IntegerField(default='1')),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.twisting_preroll_half_manuf')),
            ],
        ),
        migrations.CreateModel(
            name='Twisting_Preroll_1g_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='1g_pre_roll', max_length=120)),
                ('pre_roll_amt', models.IntegerField(default='1')),
                ('input1_amt', models.IntegerField(default='1')),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.pre_roll_1g_manuf')),
            ],
        ),
        migrations.CreateModel(
            name='Production_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.DateTimeField(blank=True, null=True)),
                ('End_time', models.DateTimeField(blank=True, null=True)),
                ('Count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Count2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('UID', models.IntegerField(default=0)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.tasks')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Tube_2half_grams_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='Preroll_tube_2_half_grams', max_length=120)),
                ('finished_2half_amt', models.IntegerField(default='1')),
                ('input1_amt', models.IntegerField(default='2')),
                ('input2', models.CharField(default='Tube', max_length=120)),
                ('input2_amt', models.IntegerField(default='1')),
                ('input3', models.CharField(default='Tube_Sticker', max_length=120)),
                ('input3_amount', models.IntegerField(default='1')),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.twisting_preroll_half_manuf')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Tube_1_gram_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='Preroll_tube_1_gram', max_length=120)),
                ('finished_amt', models.IntegerField(default='1')),
                ('input1_amt', models.IntegerField(default='1')),
                ('input2', models.CharField(default='Tube', max_length=120)),
                ('input2_amt', models.IntegerField(default='1')),
                ('input3', models.CharField(default='Tube_Sticker', max_length=120)),
                ('input3_amount', models.IntegerField(default='1')),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.twisting_preroll_1g_manuf')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Box_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(default='Finished_Box', max_length=120)),
                ('finished_box_amt', models.IntegerField(default='1')),
                ('input1_amt', models.IntegerField(default='1')),
                ('input2', models.CharField(default='Plastic_wrap', max_length=120)),
                ('input2_amt', models.IntegerField(default='1')),
                ('input3', models.CharField(default='Ribbon', max_length=120)),
                ('input3_amt', models.IntegerField(default='1')),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.unwrapped_box_manuf')),
            ],
        ),
    ]
