# Generated by Django 3.1.2 on 2020-10-19 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20201018_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='finished_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
