# Generated by Django 3.1.2 on 2020-10-19 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_delete_employee_tracker'),
        ('production', '0003_tasks_finished_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_manuf',
            name='finished_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_roll_1g_manuf',
            name='finished_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preroll_half_manuf',
            name='finished_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tube_2half_manuf',
            name='finished_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tube_full_manuf',
            name='finished_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production_tracker',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employees.employee'),
        ),
        migrations.AlterField(
            model_name='production_tracker',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.tasks'),
        ),
    ]
