# Generated by Django 3.1.2 on 2020-10-20 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20201019_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_roll_1g_manuf',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preroll_half_manuf',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pre_roll_1g_manuf',
            name='canna_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
