# Generated by Django 3.1.2 on 2020-10-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20201019_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='preroll_half_manuf',
            name='input1',
            field=models.CharField(default='cone', max_length=120),
        ),
        migrations.AddField(
            model_name='preroll_half_manuf',
            name='input2',
            field=models.CharField(default='cannabis', max_length=120),
        ),
    ]
