# Generated by Django 3.1.2 on 2020-10-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_twisting_preroll_half_manuf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twisting_preroll_half_manuf',
            name='input1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.preroll_half_manuf'),
        ),
    ]
