# Generated by Django 3.1.2 on 2020-10-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_production_tracker_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unwrapped_Box_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(max_length=120)),
                ('finished_box_amt', models.IntegerField()),
                ('pre_roll_amt', models.IntegerField()),
                ('box_amt', models.IntegerField()),
                ('input2', models.CharField(default='Label', max_length=120)),
                ('label_amount', models.IntegerField()),
                ('input3', models.CharField(default='cannasticker', max_length=120)),
                ('canna_sticker_amount', models.IntegerField()),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.twisting_preroll_half_manuf')),
            ],
        ),
        migrations.DeleteModel(
            name='Box_manuf',
        ),
    ]
