# Generated by Django 3.1.2 on 2020-10-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_auto_20201020_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='unwrapped_box_manuf',
            name='input4',
            field=models.CharField(default='cannasticker', max_length=120),
        ),
        migrations.AlterField(
            model_name='unwrapped_box_manuf',
            name='input2',
            field=models.CharField(default='Box', max_length=120),
        ),
        migrations.AlterField(
            model_name='unwrapped_box_manuf',
            name='input3',
            field=models.CharField(default='Label', max_length=120),
        ),
    ]
