# Generated by Django 3.1.2 on 2020-10-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_auto_20201020_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Box_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(max_length=120)),
                ('finished_box_amt', models.IntegerField()),
                ('input1_amt', models.IntegerField()),
                ('input2', models.CharField(default='Plastic_wrap', max_length=120)),
                ('input2_amt', models.IntegerField()),
                ('input3', models.CharField(default='Ribbon', max_length=120)),
                ('input3_amount', models.IntegerField()),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.unwrapped_box_manuf')),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Tube_2half_grams_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(max_length=120)),
                ('finished_2half_amt', models.IntegerField()),
                ('input1_amt', models.IntegerField()),
                ('input2', models.CharField(default='Tube', max_length=120)),
                ('input2_amt', models.IntegerField()),
                ('input3', models.CharField(default='Sticker', max_length=120)),
                ('input3_amount', models.IntegerField()),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.twisting_preroll_half_manuf')),
            ],
        ),
        migrations.DeleteModel(
            name='tube_2half_manuf',
        ),
    ]
