# Generated by Django 3.1.2 on 2020-10-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_auto_20201020_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Tube_1_gram_manuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.CharField(max_length=120)),
                ('finished_2half_amt', models.IntegerField()),
                ('input1_amt', models.IntegerField()),
                ('input2', models.CharField(default='Tube', max_length=120)),
                ('input2_amt', models.IntegerField()),
                ('input3', models.CharField(default='Sticker', max_length=120)),
                ('input3_amount', models.IntegerField()),
                ('input1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.pre_roll_1g_manuf')),
            ],
        ),
        migrations.DeleteModel(
            name='tube_full_manuf',
        ),
    ]
