# Generated by Django 3.1.2 on 2020-10-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_auto_20201020_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finished_tube_1_gram_manuf',
            old_name='finished_2half_amt',
            new_name='finished_amt',
        ),
    ]
