# Generated by Django 3.1.2 on 2020-10-29 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(blank=True, max_length=120, null=True)),
                ('supply_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_units_in_box', models.IntegerField(blank=True, null=True)),
                ('price_of_box', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('UID', models.IntegerField(blank=True, null=True)),
                ('cost_of_task', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
