# Generated by Django 3.1.2 on 2020-10-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(max_length=120)),
                ('supply_amt', models.IntegerField()),
                ('per_box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplies_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(max_length=120)),
                ('supply_amt', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee_tracker')),
            ],
        ),
    ]
