# Generated by Django 3.1.2 on 2020-10-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employee'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies_log',
            name='Emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee'),
        ),
    ]
