# Generated by Django 3.1.2 on 2020-10-19 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_delete_employee_tracker'),
        ('inventory', '0002_auto_20201018_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(max_length=120)),
                ('supply_amt', models.IntegerField()),
                ('Date', models.DateField()),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.RenameModel(
            old_name='Supplies',
            new_name='Inventory',
        ),
        migrations.DeleteModel(
            name='Supplies_Log',
        ),
    ]
