# Generated by Django 3.1.2 on 2020-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201018_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='inventory_log',
            name='per_box',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory_log',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
