# Generated by Django 3.1.2 on 2020-10-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201019_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_log',
            name='per_box',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
