# Generated by Django 3.1.2 on 2020-10-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20201019_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_log',
            name='UID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
